name: Ruby

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rails 2.6
      run: |
        sudo gem install rails -v 6.0.2
    - name: Build and test with Rake
      run: |
        ruby -v
        sudo gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
